# Generated by Django 4.1.3 on 2022-12-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_alter_snack_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snack',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'my snacks'},
        ),
    ]
